name: MLOps CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install .
          

      - name: Run tests
        run: |
          uv run -- PYTHONPATH=. pytest

      - name: Check DVC reproducibility
        run: |
          dvc repro


