name: MLOps CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-    

      - name: Install dependencies
        run: |
          python -m pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install .
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Write GCP credentials from secret
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > gcp-creds.json

      - name: Configure DVC remote with GCS
        run: |
          source .venv/bin/activate
          dvc remote add -d -f gcs gs://durga_dvc/telco_churn_data
          dvc remote modify gcs credentialpath gcp-creds.json  

      - name: Pull tracked data from DVC
        run: |
          source .venv/bin/activate
          dvc pull

      - name: Check DVC reproducibility
        run: |
          dvc repro    

      - name: Run tests
        run: |
          export PYTHONPATH=.
          pytest


      


